### ISSUE TITLE
flow_ebos default output directory

### ISSUE THREAD

**Issue by nairr** [OPM/opm-output#173]
I observe that when using the current build of OPM and with default settings the flow_ebos output files(.PRT, .UNRST etc) are written out within the current/working directory instead of directory containing the .DATA file

**Comment by atgeirr** [comment]
That sounds sensible to me, do you find it surprising or wrong?

**Comment by nairr** [comment]
Its of course open to discussion, but as a user I would prefer to have the output files connected to a particular data file to be present in the directory containing the .DATA file, so as to avoid confusion (when having decks with similar names etc.) and please correct me if I am wrong, but I believe it also the convention that Eclipse follows.

**Comment by bska** [comment]
> but I believe [output in same directory as .DATA file is] also the convention that Eclipse follows.

It is.  ECLIPSE uses the directory containing the simulation deck (i.e., the `.DATA` file) as its working directory and writes all of its output to that directory.  I think I'd like an option of putting the output someplace else in a particular run, but the default should be to write the output to the `.DATA` directory.

**Comment by andlaus** [comment]
stupid question: won't you get the behaviour which you want by simply starting the simulator from the same directory that contains the data file, i.e. by starting the simulator using `(cd $DATA_DIR; flow_ebos $FOO.DATA)` instead of `flow_ebos $DATA_DIR/$FOO.DATA`? (IMO, placing the output files into the current working directory is somewhat simpler to implement, less surprising if you're not coming from the ECL world and more versatile.)
